apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rvk5zuycz-python
  janus-idp.io/tekton: rvk5zuycz-python
  backstage.io/kubernetes-id: rvk5zuycz-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rvk5zuycz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
